SELECT * FROM MOVIES; /* #1 */

SELECT * FROM genres; /* #2 */

SELECT * FROM STUDIOS WHERE studio_active = 1; /* #3*/

SELECT * FROM members ORDER BY MEMBER_DISCHARGE_DATE DESC LIMIT 10; /* #4 */


SELECT * 
FROM (
		SELECT MOVIES.MOVIE_DURATION, COUNT(*) AS REGISTROS_REPETIDOS 
		FROM MOVIES
		GROUP BY MOVIES.MOVIE_DURATION
		ORDER BY REGISTROS_REPETIDOS DESC
		LIMIT 20)
ORDER BY MOVIE_DURATION DESC; /* #5 */

